name: 💬 Open Topic
description: Share ideas, tech questions, or open-ended thoughts.
title: "[Open]"
labels: ["discussion"]
assignees: ["atsushifx"]

body:
  - type: dropdown
    id: category
    attributes:
      label: 🏷 Topic Type
      description: Select the category that best fits your message.
      options:
        - 💬 General Topic
        - 🛠 Technical Question
        - 🌱 Idea or Concept
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💡 What would you like to discuss?
      description: Feel free to share your thoughts, questions, or feedback.
      placeholder: |
        I have an idea for improving the onboarding experience...
        or:
        I want to discuss dependency versioning strategies.

  - type: textarea
    attributes:
      label: 📎 Context or references (optional)
      description: Provide any related links, documents, or notes.
      placeholder: |
        Related to PR #42 and onboarding.md

  - type: markdown
    attributes:
      value: |
        ---
        🤖 This project is supported by AI chatbots: **Elpha**, **Kobeni**, and **Tsumugi**.

        > If the topic becomes active, we may move the conversation to [GitHub Discussions](https://github.com/atsushifx/discussions) for better tracking and visibility.
