# src: .markdownlint.yaml
## @(#) : markdown linter
#
# @version  1.0.2
# @author   atsushifx <https://github.com/atsushifx>
# @since    2025-04-25
# @license  MIT
#
# @description<<
#
# Basic markdownlint settings for consistent formatting and readability.
# For use with: markdownlint-cli2
#
#<<

# Enable default markdownlint rules
default: true

# Custom lint rules
whitespace: true

line-length:
  line_length: 120
  code_block_line_length: 120

ol-prefix: true

emphasis-style:
  style: asterisk

strong-style:
  style: asterisk

no-hard-tabs: true
